### ISSUE TITLE
"issuesベース開発"レビュー依頼

### ISSUE THREAD

**Issue by monakon** [monakon/portfolio#35]
### 概要
卒業制作で旅の記録を投稿・閲覧できるアプリを作成予定です。
実装予定の機能と必要なページを以下に書き出しました。
ご確認よろしくお願いいたします。

＜使用している言葉の補足＞
- 「投稿」＝旅の記録を作成して投稿する

### 実装予定の機能
- [ ] 旅の記録作成・投稿機能
- [ ] 投稿閲覧機能
- [ ] 投稿編集・削除機能
- [ ] 投稿検索・一覧表示機能
- [ ] ユーザ登録機能
- [ ] ログイン・ログアウト機能
- [ ] プロフィール編集機能
- [ ] パスワード変更設定機能

### 必要なページ
- [ ] トップページ
- [ ] ユーザ登録ページ
- [ ] ログインページ
- [ ] みんなの投稿一覧ページ
- [ ] 自分の投稿一覧ページ
- [ ] 投稿詳細ページ
- [ ] 検索結果一覧ページ
- [ ] 投稿作成ページ
- [ ] マイページ
- [ ] プロフィールページ
- [ ] プロフィール編集ページ
- [ ] パスワード変更設定ページ
- [ ] パスワード変更設定メール送信完了ページ
- [ ] ヘッダー（ログイン前）
- [ ] ヘッダー（ログイン中）

**Comment by monakon** [comment]
本日、Projectがprivateになってしまっていたのでpublicに設定を変更しました。
6/5に提出しましたが、見れる状態でなかったと思うので上記設定を変更し、再提出させてもらいました。すみません。

**Comment by ky0613** [comment]
ご提出ありがとうございます。
以下コメントになります。

----

- 調査などのカードにもストーリーポイントの設定をお願いします。

**Comment by monakon** [comment]
お世話になります。
コメントありがとうございます。
以下について変更しましたので再提出します。

・【調査】カードも含め全てのisuueにストーリーポイントを設定しました

ご確認よろしくお願いいたします。

**Comment by Tsuchiya2** [comment]
対応ありがとうございます。LGTMです。

---

以下、MVPに含めなくて良いかもと思ったものになります。

- Google認証
- 舞台にする場所を地図から取得する
- プロフィール
- パスワード変更
- マイページ

**Comment by monakon** [comment]
お世話になります。
確認していただき、ありがとうございます。

MVPに含めなくていい機能として提示いただいた分は、MVPから削ろうと思います。まず、最低限の機能でデプロイすることを目標にします！
